title: Dayavihar Consulting
description: Web development on Ruby on Rails
google_analytics: 
show_downloads: false
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
